### PR TITLE
Fix for #95  RM with mailer block syntax leads to errors (symbolize keys)

### PR DESCRIPTION
**Pull request by jogaco**
Did not do any test. Would probably need an integration test.
Unit tests are passing

### CODE REVIEW

**Comment by zapnap** [comment]
Looks good, thanks!

**Comment by ebeigarts** [comment]
What is mailer block syntax? Can we turn this off? we are currently passing `changes = { "field1" => "value", "field2" => "value" }` and doing `changes.each do |key, value|` in mailer view, and we now see duplicate entries, so we need additional logic to remove symbolized keys from hash, anyway this was unexpected.

**Comment by ebeigarts** [comment]
Ok, this is actually #101 what is causing this, so the has end up looking like `{ "field1" => "value", "field2" => "value", :field1 => "value", :field2 => "value"  }`

**Comment by jogaco** [comment]
Example:
`Notifier.send_simple_message(:from => 'user1@example.com', :to => 'user2@example.com', :subject => 'subject', :body => 'body').deliver`

If removed, this would not work.

**Comment by jogaco** [comment]
Internal implementation of `ActionMailer::Base` needs symbols. If they are not there, it doesn't work

**Comment by jogaco** [comment]
In #100 A compromise was adopted to have keys as string and duplicated as symbol, so block syntax to send mails without templates would work, whereas keys as strings were still present.

**Comment by ebeigarts** [comment]
Wouldn't it be better to use `.with_indifferent_access`, so that it doesn't have duplicate keys?

```
> h = { "to" => "value" }.with_indifferent_access
> h[:to]
"value"
> h["to"]
"value"
> h.size
1
```

**Comment by ebeigarts** [comment]
Also I think it should be handled by `argument_serializer`, so that there is way this can be turned off. maybe two different serializers `PassThruSerializer` and `IndifferentAccessSerializer`?

**Comment by jogaco** [comment]
It would require to modify a core rails library, so it accepts calls from an external library. Doesn't sound good to me.

**Comment by jogaco** [comment]
The option of `with_indifferent_access` might actually work

**Comment by zapnap** [comment]
Should test (PR?) but sounds right to me.

..nap

On Thu, Sep 14, 2017 at 11:29 AM "J. Garcia"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

The option of

with_indifferent_access

might actually work

—

You are receiving this because you modified the open/close state.

Reply to this email directly,
https://github.com/zapnap/resque_mailer/pull/97#issuecomment-329518861
, or

**Comment by jogaco** [comment]
Having a look at it

**Comment by jogaco** [comment]
Tests work with the option of with_indifferent_access.
PR #102 submitted

**Pull request merged**
