### PR TITLE
Improved fix for #95 and #100

### PR DESCRIPTION
**Pull request by jogaco**

### CODE REVIEW

**Comment by ebeigarts** [comment]
@jogaco thanks :)

**Comment by zapnap** [comment]
Merged! If it's working for you (pls confirm) I'll cut a new gem.

**Comment by ebeigarts** [comment]
@zapnap I will try to test this today and will let you know

**Comment by ebeigarts** [comment]
@zapnap it works! please release a new gem, thanks :)

**Comment by zapnap** [comment]
Done -- thanks all

**Comment by tf** [comment]
This PR broke our gem again. To work around the breaking change in #97 (which turned string keys into smybol keys, see #100) and before #101 was released, we added an `options.symbolize_keys!` call to support all versions of this gem. `symbolize_keys!` has now been removed by this PR in 2.4.3 since `HashWithIndifferentAccess` does not support it.

**Pull request merged**
