### PR TITLE
Rails 5 Compatibility

### PR DESCRIPTION
**Pull request by spilth**
In Rails 5 ActionMailer no longer automatically calls `process` when initialized so it needs to be called manually:

https://github.com/rails/rails/commit/e76c38ef1047ad3ffb25c1c639c38432a9228796

### CODE REVIEW

**Comment by ErebusBat** [comment]
👍

**Comment by reneklacan** [comment]
@spilth this should probably include changes to travis to include Rails 5 and new ruby as well... and Rails 5 tests should only run on new Ruby

@zapnap What would you ideally want to do? Support only rails 5 with new versions? Or ideally simultaneously support Rails 4 and 5? (I think at least Rails 3 support can be dropped)... What do you think?

**Comment by zapnap** [comment]
Cool. I'd like to keep legacy support for Rails 3+ until the next major release. Nixing support for anything but Rails 5 is certainly not an option right now (outside of a branch anyway). Our policy thus far has been to try to support multiple production versions in parallel, which hasn't presented huge issues to date. Agree that we'd want to see travis changes in this PR.

**Comment by zapnap** [comment]
Rails 5 was just released so if you'd like to update this with the comments above I'd be happy to pull it in. Lmk, thanks!

**Comment by nimashariatian** [comment]
how long until this is ready? it would be great to merge this! 
👍

**Comment by zapnap** [comment]
As noted, I'd be happy to merge a changeset to support Rails 5 if backwards compatibility is preserved and scenarios / tests are added in Travis. This is definitely a priority as Rails 5 is now released, I just haven't had the free time to get to it myself. If you'd like to make those changes I'd be happy to take a look.

**Comment by zapnap** [comment]
@nimashariatian @ErebusBat @reneklacan @spilth Please see the Rails 5 compat branch and comments on #90 thanks!

**Comment by zapnap** [comment]
The work in #90 seems to be working fine for me on an older project as well as on the latest 5.0.0 release. Going to go ahead and merge to master. If someone else here can please verify that it's working as well, that'd be appreciated prior to a proper gem release. Please move conversation to #90 thanks!

**Comment by zapnap** [comment]
@nimashariatian can you confirm this is working for you?

**Comment by nimashariatian** [comment]
@zapnap pointing to master and seems to be working!

**Comment by zapnap** [comment]
v2.4.0 has been released -- thanks!

**Pull request closed without merging**
